import { describe, expect, it, vi } from 'vitest';
import type { LocationProfile } from '@policylab/shared';
import type { AgentBlueprint } from '../../data/dataBootstrapPipeline.js';
import type { LLMMessage, LLMOptions, LLMProvider, TestConnectionResult } from '../../llm/types.js';
import { enrichRosterBatch, parseAndValidateRosterBatch } from '../bootstrapRoster.js';

function makeProfile(): LocationProfile {
  return {
    countryCode: 'CN',
    countryName: 'China',
    locationName: 'Hangzhou',
    coordinates: { lat: 30.2741, lon: 120.1551 },
    demographics: {},
    economics: {},
    fiscal: {},
    fetchedAt: new Date().toISOString(),
  } as unknown as LocationProfile;
}

function makeBlueprints(count: number): AgentBlueprint[] {
  return Array.from({ length: count }, (_value, index) => ({
    name: `Agent-${index + 1}`,
    role: 'WORKER',
    sector: 'industry',
    initialWealth: 100,
    background: 'background to be generated by llm',
  })) as unknown as AgentBlueprint[];
}

type MockProvider = LLMProvider & {
  chat: ReturnType<typeof vi.fn<[LLMMessage[], LLMOptions?], Promise<string>>>;
  chatStream: ReturnType<typeof vi.fn<[LLMMessage[], LLMOptions?], AsyncIterable<string>>>;
  testConnection: ReturnType<typeof vi.fn<[], Promise<TestConnectionResult>>>;
};

function createMockProvider(responses: string[]): MockProvider {
  let index = 0;
  return {
    chat: vi.fn<[LLMMessage[], LLMOptions?], Promise<string>>(async () => (
      responses[index++] ?? responses[responses.length - 1] ?? '{"agents":[]}'
    )),
    chatStream: vi.fn<[LLMMessage[], LLMOptions?], AsyncIterable<string>>(async function* () {}),
    testConnection: vi.fn(async () => ({ ok: true, model: 'mock', latencyMs: 1 })),
  };
}

describe('parseAndValidateRosterBatch', () => {
  it('rejects undersized arrays', () => {
    expect(() =>
      parseAndValidateRosterBatch(
        '{"agents":[{"name":"Anya Schmidt","background":"One"}]}',
        2,
        0,
      )).toThrow(/expected 2 agents, got 1/i);
  });

  it('rejects implausible names — long runs of dots and question marks (real local-LLM degenerate output)', () => {
    expect(() =>
      parseAndValidateRosterBatch(
        '{"agents":[{"name":"Marlon Schwarz ... ..............?? ...???????..??.. ........","background":"non-empty"}]}',
        1,
        0,
      )).toThrow(/implausible name/i);
  });

  it('rejects implausible names — punctuation-only', () => {
    expect(() =>
      parseAndValidateRosterBatch(
        '{"agents":[{"name":"......","background":"non-empty"}]}',
        1,
        0,
      )).toThrow(/implausible name/i);
  });

  it('accepts valid culturally-appropriate names', () => {
    const out = parseAndValidateRosterBatch(
      '{"agents":[{"name":"Marlene Fischer","background":"works at the local clinic"},{"name":"Li Xiaofeng","background":"fisher"}]}',
      2,
      0,
    );
    expect(out).toHaveLength(2);
    expect(out[0]?.name).toBe('Marlene Fischer');
    expect(out[1]?.name).toBe('Li Xiaofeng');
  });
});

describe('enrichRosterBatch', () => {
  it('splits a partial local-model batch into smaller requests', async () => {
    const provider = createMockProvider([
      '{"agents":[{"name":"Only One","background":"First attempt returned a partial roster."}]}',
      '{"agents":[{"name":"Li Xiaofeng","background":"He grew up in a fishing village and saves cautiously after repeated flood losses."}]}',
      '{"agents":[{"name":"Chen Mei","background":"She learned trade from her mother and takes measured risks when supply prices shift."}]}',
    ]);

    const agents = await enrichRosterBatch({
      provider,
      profile: makeProfile(),
      batchBlueprints: makeBlueprints(2),
      batchStart: 0,
    });

    expect(agents).toHaveLength(2);
    expect(agents[0]?.name).toBe('Li Xiaofeng');
    expect(agents[1]?.name).toBe('Chen Mei');
    expect(provider.chat).toHaveBeenCalledTimes(3);
  });
});
